apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app: movies
  ports:
    - port: 80          # porta deste serviço
      targetPort: 5000  # porta do Container
      nodePort: 30000
  type: NodePort